name: pals0039
channels:
  - defaults
dependencies:
  - matplotlib
  - numpy-base
  - numpydoc
  - pandas
  - pandoc
  - pandocfilters
  - pip
  - scikit-learn
  - scipy
  - tensorflow
  - tensorflow-base
  - urllib3
  - pip:
    - h5py
    - keras
    - keras-applications
    - keras-preprocessing
    - numpy

